### ISSUE TITLE
dtkLogger

### ISSUE THREAD

**Issue by LoicCadour** [d-tk/dtk#6]
I am trying to integrate the dtkLogger inside medInria, and it works very well.
Maybe two features that might be interesting would be to:
* allow to set a maximum size for the log file, so that it doesn't explode,
* and, this one might be more difficult, to allow multiple log levels according to the destination. For instance, you might want to see debug messages in the console, but just errors and warnings in the dtkLogView.

**Comment by nniclausse** [comment]
first feature done. Second one: you already have the possibility to filter out any level you want with dtkLogView (e.g. dtkWidgetsLogView::displayTrace(false))
